title: My Github Page (with jekyll) ✨
author: Chellx (Michelle)
email: your-email@domain.com
description: My GitHub page using jekyll! 
  
theme: jekyll-theme-architect

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  Chellx # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
